# Generated by Django 4.1.3 on 2023-03-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210629_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('userName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('password1', models.CharField(max_length=120)),
                ('paasword2', models.CharField(max_length=120)),
            ],
        ),
    ]
