# Generated by Django 4.1.3 on 2023-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_hotel_hotel_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='Upload_Your_Image',
        ),
    ]
