# Generated by Django 4.1.3 on 2023-04-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_hotel_hotel_main_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='hotel_Main_Img',
            new_name='Main_Img',
        ),
    ]
