# Generated by Django 4.1.3 on 2023-04-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_name_hotel_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='Upload_Your_Image',
            new_name='hotel_Main_Img',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='Name',
            new_name='name',
        ),
    ]
