# Generated by Django 4.1.3 on 2023-05-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_main_img_image_upload_your_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='media/images'),
        ),
    ]
