# Generated by Django 4.1.3 on 2023-05-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_signup_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='Quiz2\\media\\images'),
        ),
    ]
