# Generated by Django 4.1.3 on 2023-05-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_signup_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='profile_pic',
        ),
    ]
